### ISSUE TITLE
Remove Fatalf call from serveAPI

### ISSUE THREAD

**Issue by yitsushi** [weaveworks-liquidmetal/flintlock#235]
**Describe the solution you'd like:**
Right now the code has a `TODO` mark, so just resolve it.

**Why do you want this feature:**
No `TODO` comments should live in the code without filed issues to track them.

**Anything else you would like to add:**
https://github.com/weaveworks/flintlock/blob/main/internal/command/run/run.go#L145

**Comment by richardcase** [comment]
Exit in a more friendly and graceful way

**Comment by richardcase** [comment]
This is still needed

**Comment by yitsushi** [comment]
Still valid.
