### ISSUE TITLE
Reconciliation continually loops and creates 100s/1000s network interface

### ISSUE THREAD

**Issue by richardcase** [weaveworks-liquidmetal/flintlock#261]
**What happened:**

When calling create flintlock went in to an infinite loop and it created 1700+ network interfaces before i killed the process.

Needs more investigation.

**What did you expect to happen:**

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
I haven't seen this issue for a while now.

**Comment by yitsushi** [comment]
Can we close this? I don't think we met this issue in the last 1.5-2 months.
