### ISSUE TITLE
Fix flintlock to work with firecracker v1.0.0

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/flintlock#390]
With latest changes mvms can't get the mmds service so cloud-init is falling back to its defaullt.

See thread [here](https://weaveworks.slack.com/archives/C01SYJ779SR/p1644584683063979).

Some changes to make flintlock compatible did go into 0.1.0-alpha.7, but this did not solve everything.

**Comment by richardcase** [comment]
Changes were undone in #393

**Comment by Callisto13** [comment]
We have decided to drop this.

Macvtap will not be merged into main of firecracker this year, so we are going to leave flintlock as compatible with firecracker `0.25.2`, mark our firecracker implementation as experimental, and proceed with making could hypervisor the default.
