### ISSUE TITLE
Update provision.sh to start the server with auth

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/flintlock#539]
Right now the `provision.sh` defaults to setting `insecure: true` on the flintlockd config. There is no option to run in secure mode.

We need to expose options for people to start flintlockd with certs _that they bring_.

For example:

```bash
./provision.sh flintlock --basic-auth-token foobar
./provision.sh all --basic-auth-token foobar

./provision.sh flintlock --tls-cert <path> --tls-client-ca <path> --tls-key <path> --tls-client-validate
./provision.sh all --tls-cert <path> --tls-client-ca <path> --tls-key <path> --tls-client-validate
```

This adds a lot of flags to the `all` and the `flintlock` subcommands, so we may also want to add a `--config` flag to them in case people simple want to bring their own yaml. This can be done in a separate PR if the work here is already big enough.

Another option is to have a `--fl-extra-args` flag which could receive a string of k=v pairs which are parsed and written to flintlock's config.

**Comment by Skarlso** [comment]
Going to take this one. :)

**Comment by Callisto13** [comment]
👍 sounds good
