### ISSUE TITLE
SMT (Simultaneous Multithreading) is not supported by firecracker on ARM

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/flintlock#558]
We currently hardcode this to `true` [here](https://github.com/weaveworks-liquidmetal/flintlock/blob/70e020d245bf61bf7cdd9f60c1c24a8fb3d74505/infrastructure/firecracker/config.go#L42).

Options:
- We expose a point in the API where this can be set `enable_smt` (default `true`) or `disable_smt` (default `false`)
- We expose nothing and detect. If `aarch` we set to false.

Thoughts @richardcase ?

**Comment by richardcase** [comment]
> Options:
> 
>     * We expose a point in the API where this can be set `enable_smt` (default `true`) or `disable_smt` (default `false`)
> 
>     * We expose nothing and detect. If `aarch` we set to false.

Personally, i think we should start with detecting the architecture in the firecracker provider and then setting `smt` accordingly...so seconf option.
